steps:
  # 1. Fazer build da imagem Docker e enviar para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/meu-repo/meu-streamlit-app:$SHORT_SHA',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/meu-repo/meu-streamlit-app:$SHORT_SHA'
      ]

  # 2. Fazer o deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'run',
        'deploy',
        'meu-streamlit-app', # Nome do serviço no Cloud Run
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/meu-repo/meu-streamlit-app:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/meu-repo/meu-streamlit-app:$SHORT_SHA'
  
options:
  logging: CLOUD_LOGGING_ONLY